import type { AuditEvent, Capability, CapabilityPromotion, ConfigurationRevision, ExecutionPlan, ExecutionResult, IdempotencyRecord, Incident, LearningSignal, OptimizationProposal, OutcomeRecord, PerformanceMeasurement, Policy, RecoveryRecord, Run, SafeStop, Task, TelemetryRecord, Workspace } from '../domain/models'
import type { Repository } from '../ports/repository'

type Row = Record<string, unknown>
const json = (value: unknown) => JSON.stringify(value)
const parse = <T>(value: unknown): T => JSON.parse(String(value)) as T

const workspace = (r: Row): Workspace => ({ id: String(r.id), slug: String(r.slug), name: String(r.name), description: String(r.description), status: r.status as Workspace['status'], ownerId: String(r.owner_id), environment: String(r.environment), createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const capability = (r: Row): Capability => ({ id: String(r.id), name: String(r.name), description: String(r.description), ownerScope: r.owner_scope as Capability['ownerScope'], workspaceId: r.workspace_id ? String(r.workspace_id) : null, riskLevel: r.risk_level as Capability['riskLevel'], inputSchema: parse(r.input_schema), outputSchema: parse(r.output_schema), status: r.status as Capability['status'], createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const policy = (r: Row): Policy => ({ id: String(r.id), name: String(r.name), workspaceId: String(r.workspace_id), subject: String(r.subject), resource: String(r.resource), action: String(r.action), scope: String(r.scope), effect: r.effect as Policy['effect'], approvalRequired: Boolean(r.approval_required), status: r.status as Policy['status'], createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const task = (r: Row): Task => ({ id: String(r.id), workspaceId: String(r.workspace_id), title: String(r.title), description: String(r.description), status: r.status as Task['status'], capabilityId: r.capability_id ? String(r.capability_id) : null, credentialRef: r.credential_ref ? String(r.credential_ref) : null, createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const run = (r: Row): Run => ({ id: String(r.id), taskId: String(r.task_id), workspaceId: String(r.workspace_id), status: r.status as Run['status'], attempt: Number(r.attempt ?? 0), idempotencyKey: r.idempotency_key ? String(r.idempotency_key) : null, startedAt: r.started_at ? String(r.started_at) : null, completedAt: r.completed_at ? String(r.completed_at) : null, error: r.error ? String(r.error) : null, createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const plan = (r: Row): ExecutionPlan => ({ id: String(r.id), taskId: String(r.task_id), workspaceId: String(r.workspace_id), steps: parse(r.steps), status: r.status as ExecutionPlan['status'], overallTimeoutSeconds: Number(r.overall_timeout_seconds), createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const result = (r: Row): ExecutionResult => ({ id: String(r.id), taskId: String(r.task_id), runId: String(r.run_id), workspaceId: String(r.workspace_id), stepId: String(r.step_id), status: r.status as ExecutionResult['status'], output: r.output ? parse(r.output) : null, errorCode: r.error_code ? String(r.error_code) : null, errorMessage: r.error_message ? String(r.error_message) : null, createdAt: String(r.created_at) })
const idempotency = (r: Row): IdempotencyRecord => ({ key: String(r.key), workspaceId: String(r.workspace_id), capabilityId: String(r.capability_id), status: r.status as IdempotencyRecord['status'], resultId: r.result_id ? String(r.result_id) : null, createdAt: String(r.created_at), updatedAt: String(r.updated_at) })
const event = (r: Row): AuditEvent => ({ id: String(r.id), type: r.type as AuditEvent['type'], actor: parse(r.actor), workspaceId: r.workspace_id ? String(r.workspace_id) : null, resourceType: String(r.resource_type), resourceId: String(r.resource_id), timestamp: String(r.timestamp), metadata: parse(r.metadata) })
const incident = (r: Row): Incident => ({ id: String(r.id), severity: r.severity as Incident['severity'], workspaceId: String(r.workspace_id), taskId: r.task_id ? String(r.task_id) : null, runId: r.run_id ? String(r.run_id) : null, category: r.category as Incident['category'], summary: String(r.summary), status: r.status as Incident['status'], detectedAt: String(r.detected_at), resolvedAt: r.resolved_at ? String(r.resolved_at) : null, metadata: parse(r.metadata) })
const safeStop = (r: Row): SafeStop => ({ id: String(r.id), scope: r.scope as SafeStop['scope'], scopeId: String(r.scope_id), workspaceId: r.workspace_id ? String(r.workspace_id) : null, reason: String(r.reason), active: Boolean(r.active), triggeredBy: parse(r.triggered_by), triggeredAt: String(r.triggered_at), releasedBy: r.released_by ? parse(r.released_by) : null, releasedAt: r.released_at ? String(r.released_at) : null })
const recovery = (r: Row): RecoveryRecord => ({ id: String(r.id), workspaceId: String(r.workspace_id), taskId: String(r.task_id), runId: String(r.run_id), outcome: r.outcome as RecoveryRecord['outcome'], status: r.status as RecoveryRecord['status'], strategy: r.strategy as RecoveryRecord['strategy'], createdAt: String(r.created_at), completedAt: r.completed_at ? String(r.completed_at) : null, metadata: parse(r.metadata) })
const telemetry = (r: Row): TelemetryRecord => ({ id: String(r.id), correlationId: String(r.correlation_id), taskId: r.task_id ? String(r.task_id) : null, runId: r.run_id ? String(r.run_id) : null, workspaceId: r.workspace_id ? String(r.workspace_id) : null, capabilityId: r.capability_id ? String(r.capability_id) : null, actor: parse(r.actor), timestamp: String(r.timestamp), durationMs: r.duration_ms === null ? null : Number(r.duration_ms), status: String(r.status), errorClass: r.error_class ? r.error_class as TelemetryRecord['errorClass'] : null, retryCount: Number(r.retry_count), policyOutcome: r.policy_outcome as TelemetryRecord['policyOutcome'], metadata: parse(r.metadata) })
const outcome = (r: Row): OutcomeRecord => ({ id:String(r.id),workspaceId:String(r.workspace_id),taskId:String(r.task_id),runId:String(r.run_id),capabilityId:String(r.capability_id),versionId:String(r.version_id),status:r.status as OutcomeRecord['status'],startedAt:String(r.started_at),completedAt:String(r.completed_at),durationMs:Number(r.duration_ms),attempts:Number(r.attempts),retries:Number(r.retries),policyOutcome:r.policy_outcome as OutcomeRecord['policyOutcome'],errorClass:r.error_class as OutcomeRecord['errorClass'],metrics:parse(r.metrics),sourceType:r.source_type as OutcomeRecord['sourceType'],sourceId:String(r.source_id),verified:Boolean(r.verified),capturedAt:String(r.captured_at) })
const signal = (r: Row): LearningSignal => ({ id:String(r.id),workspaceId:String(r.workspace_id),targetType:r.target_type as LearningSignal['targetType'],targetId:String(r.target_id),versionId:String(r.version_id),signalType:r.signal_type as LearningSignal['signalType'],value:Number(r.value),sampleSize:Number(r.sample_size),outcomeRefs:parse(r.outcome_refs),validationStatus:r.validation_status as LearningSignal['validationStatus'],confidence:Number(r.confidence),createdAt:String(r.created_at) })
const proposal = (r: Row): OptimizationProposal => ({ id:String(r.id),workspaceId:String(r.workspace_id),targetType:r.target_type as OptimizationProposal['targetType'],targetId:String(r.target_id),reason:String(r.reason),evidenceRefs:parse(r.evidence_refs),currentConfig:parse(r.current_config),proposedConfig:parse(r.proposed_config),expectedEffect:parse(r.expected_effect),riskClass:r.risk_class as OptimizationProposal['riskClass'],status:r.status as OptimizationProposal['status'],baseRevisionId:r.base_revision_id?String(r.base_revision_id):null,appliedRevisionId:r.applied_revision_id?String(r.applied_revision_id):null,approvalRef:r.approval_ref?String(r.approval_ref):null,createdAt:String(r.created_at),reviewedAt:r.reviewed_at?String(r.reviewed_at):null,appliedAt:r.applied_at?String(r.applied_at):null,revertedAt:r.reverted_at?String(r.reverted_at):null })
const revision = (r: Row): ConfigurationRevision => ({ id:String(r.id),workspaceId:String(r.workspace_id),targetType:r.target_type as ConfigurationRevision['targetType'],targetId:String(r.target_id),version:Number(r.version),config:parse(r.config),previousRevisionId:r.previous_revision_id?String(r.previous_revision_id):null,proposalId:r.proposal_id?String(r.proposal_id):null,status:r.status as ConfigurationRevision['status'],createdAt:String(r.created_at),activatedAt:r.activated_at?String(r.activated_at):null })
const measurement = (r: Row): PerformanceMeasurement => ({ id:String(r.id),workspaceId:String(r.workspace_id),targetType:r.target_type as PerformanceMeasurement['targetType'],targetId:String(r.target_id),versionId:String(r.version_id),period:r.period as PerformanceMeasurement['period'],outcomeRefs:parse(r.outcome_refs),metrics:parse(r.metrics),measuredAt:String(r.measured_at) })
const promotion = (r: Row): CapabilityPromotion => ({ id:String(r.id),workspaceId:String(r.workspace_id),capabilityId:String(r.capability_id),ownerId:String(r.owner_id),provenanceRefs:parse(r.provenance_refs),performanceMeasurementIds:parse(r.performance_measurement_ids),securityContract:parse(r.security_contract),scope:parse(r.scope),status:r.status as CapabilityPromotion['status'],approvalRef:r.approval_ref?String(r.approval_ref):null,createdAt:String(r.created_at),reviewedAt:r.reviewed_at?String(r.reviewed_at):null,promotedAt:r.promoted_at?String(r.promoted_at):null })

export class D1Repository implements Repository {
  constructor(private readonly db: D1Database) {}
  private async one<T>(sql: string, id: string, map: (r: Row) => T): Promise<T | null> { const row = await this.db.prepare(sql).bind(id).first<Row>(); return row ? map(row) : null }
  private async many<T>(sql: string, map: (r: Row) => T): Promise<T[]> { const result = await this.db.prepare(sql).all<Row>(); return result.results.map(map) }

  async createWorkspace(v: Workspace) { await this.db.prepare('INSERT INTO workspaces (id,slug,name,description,status,owner_id,environment,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(v.id,v.slug,v.name,v.description,v.status,v.ownerId,v.environment,v.createdAt,v.updatedAt).run() }
  getWorkspace(id: string) { return this.one('SELECT * FROM workspaces WHERE id=?', id, workspace) }
  listWorkspaces() { return this.many('SELECT * FROM workspaces ORDER BY created_at LIMIT 500', workspace) }
  async saveWorkspace(v: Workspace) { await this.db.prepare('UPDATE workspaces SET slug=?,name=?,description=?,status=?,environment=?,updated_at=? WHERE id=?').bind(v.slug,v.name,v.description,v.status,v.environment,v.updatedAt,v.id).run() }

  async createCapability(v: Capability) { await this.db.prepare('INSERT INTO capabilities (id,name,description,owner_scope,workspace_id,risk_level,input_schema,output_schema,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.name,v.description,v.ownerScope,v.workspaceId,v.riskLevel,json(v.inputSchema),json(v.outputSchema),v.status,v.createdAt,v.updatedAt).run() }
  getCapability(id: string) { return this.one('SELECT * FROM capabilities WHERE id=?', id, capability) }
  listCapabilities() { return this.many('SELECT * FROM capabilities ORDER BY created_at LIMIT 500', capability) }
  async saveCapability(v: Capability) { await this.db.prepare('UPDATE capabilities SET name=?,description=?,risk_level=?,input_schema=?,output_schema=?,status=?,updated_at=? WHERE id=?').bind(v.name,v.description,v.riskLevel,json(v.inputSchema),json(v.outputSchema),v.status,v.updatedAt,v.id).run() }

  async createPolicy(v: Policy) { await this.db.prepare('INSERT INTO policies (id,name,workspace_id,subject,resource,action,scope,effect,approval_required,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.name,v.workspaceId,v.subject,v.resource,v.action,v.scope,v.effect,v.approvalRequired ? 1 : 0,v.status,v.createdAt,v.updatedAt).run() }
  getPolicy(id: string) { return this.one('SELECT * FROM policies WHERE id=?', id, policy) }
  listPolicies() { return this.many('SELECT * FROM policies ORDER BY created_at LIMIT 500', policy) }
  async savePolicy(v: Policy) { await this.db.prepare('UPDATE policies SET name=?,subject=?,resource=?,action=?,scope=?,effect=?,approval_required=?,status=?,updated_at=? WHERE id=?').bind(v.name,v.subject,v.resource,v.action,v.scope,v.effect,v.approvalRequired ? 1 : 0,v.status,v.updatedAt,v.id).run() }

  async createTask(v: Task) { await this.db.prepare('INSERT INTO tasks (id,workspace_id,title,description,status,capability_id,credential_ref,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.title,v.description,v.status,v.capabilityId,v.credentialRef,v.createdAt,v.updatedAt).run() }
  getTask(id: string) { return this.one('SELECT * FROM tasks WHERE id=?', id, task) }
  listTasks() { return this.many('SELECT * FROM tasks ORDER BY created_at LIMIT 500', task) }
  async saveTask(v: Task) { await this.db.prepare('UPDATE tasks SET title=?,description=?,status=?,capability_id=?,credential_ref=?,updated_at=? WHERE id=?').bind(v.title,v.description,v.status,v.capabilityId,v.credentialRef,v.updatedAt,v.id).run() }

  async createRun(v: Run) { await this.db.prepare('INSERT INTO runs (id,task_id,workspace_id,status,attempt,idempotency_key,started_at,completed_at,error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.taskId,v.workspaceId,v.status,v.attempt,v.idempotencyKey,v.startedAt,v.completedAt,v.error,v.createdAt,v.updatedAt).run() }
  getRun(id: string) { return this.one('SELECT * FROM runs WHERE id=?', id, run) }
  listRuns() { return this.many('SELECT * FROM runs ORDER BY created_at LIMIT 500', run) }
  async saveRun(v: Run) { await this.db.prepare('UPDATE runs SET status=?,attempt=?,idempotency_key=?,started_at=?,completed_at=?,error=?,updated_at=? WHERE id=?').bind(v.status,v.attempt,v.idempotencyKey,v.startedAt,v.completedAt,v.error,v.updatedAt,v.id).run() }

  async createPlan(v: ExecutionPlan) { await this.db.prepare('INSERT INTO execution_plans (id,task_id,workspace_id,steps,status,overall_timeout_seconds,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(v.id,v.taskId,v.workspaceId,json(v.steps),v.status,v.overallTimeoutSeconds,v.createdAt,v.updatedAt).run() }
  getPlan(id: string) { return this.one('SELECT * FROM execution_plans WHERE id=?', id, plan) }
  async getPlanByTask(taskId: string) { const row = await this.db.prepare('SELECT * FROM execution_plans WHERE task_id=? ORDER BY created_at DESC LIMIT 1').bind(taskId).first<Row>(); return row ? plan(row) : null }
  listPlans() { return this.many('SELECT * FROM execution_plans ORDER BY created_at LIMIT 500', plan) }
  async savePlan(v: ExecutionPlan) { await this.db.prepare('UPDATE execution_plans SET steps=?,status=?,overall_timeout_seconds=?,updated_at=? WHERE id=?').bind(json(v.steps),v.status,v.overallTimeoutSeconds,v.updatedAt,v.id).run() }

  async createResult(v: ExecutionResult) { await this.db.prepare('INSERT INTO execution_results (id,task_id,run_id,workspace_id,step_id,status,output,error_code,error_message,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.taskId,v.runId,v.workspaceId,v.stepId,v.status,v.output ? json(v.output) : null,v.errorCode,v.errorMessage,v.createdAt).run() }
  getResult(id: string) { return this.one('SELECT * FROM execution_results WHERE id=?', id, result) }
  listResults() { return this.many('SELECT * FROM execution_results ORDER BY created_at LIMIT 500', result) }

  async createIdempotencyRecord(v: IdempotencyRecord) { const found = await this.getIdempotencyRecord(v.key); if (found) return false; await this.db.prepare('INSERT INTO idempotency_records (key,workspace_id,capability_id,status,result_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(v.key,v.workspaceId,v.capabilityId,v.status,v.resultId,v.createdAt,v.updatedAt).run(); return true }
  getIdempotencyRecord(key: string) { return this.one('SELECT * FROM idempotency_records WHERE key=?', key, idempotency) }
  async saveIdempotencyRecord(v: IdempotencyRecord) { await this.db.prepare('UPDATE idempotency_records SET status=?,result_id=?,updated_at=? WHERE key=?').bind(v.status,v.resultId,v.updatedAt,v.key).run() }

  async createIncident(v: Incident) { await this.db.prepare('INSERT INTO incidents (id,severity,workspace_id,task_id,run_id,category,summary,status,detected_at,resolved_at,metadata) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.severity,v.workspaceId,v.taskId,v.runId,v.category,v.summary,v.status,v.detectedAt,v.resolvedAt,json(v.metadata)).run() }
  getIncident(id: string) { return this.one('SELECT * FROM incidents WHERE id=?', id, incident) }
  listIncidents() { return this.many('SELECT * FROM incidents ORDER BY detected_at DESC LIMIT 500', incident) }
  async saveIncident(v: Incident) { await this.db.prepare('UPDATE incidents SET severity=?,category=?,summary=?,status=?,resolved_at=?,metadata=? WHERE id=?').bind(v.severity,v.category,v.summary,v.status,v.resolvedAt,json(v.metadata),v.id).run() }

  async createSafeStop(v: SafeStop) { await this.db.prepare('INSERT INTO safe_stops (id,scope,scope_id,workspace_id,reason,active,triggered_by,triggered_at,released_by,released_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.scope,v.scopeId,v.workspaceId,v.reason,v.active ? 1 : 0,json(v.triggeredBy),v.triggeredAt,v.releasedBy ? json(v.releasedBy) : null,v.releasedAt).run() }
  getSafeStop(id: string) { return this.one('SELECT * FROM safe_stops WHERE id=?', id, safeStop) }
  listSafeStops() { return this.many('SELECT * FROM safe_stops ORDER BY triggered_at DESC LIMIT 500', safeStop) }
  async saveSafeStop(v: SafeStop) { await this.db.prepare('UPDATE safe_stops SET reason=?,active=?,released_by=?,released_at=? WHERE id=?').bind(v.reason,v.active ? 1 : 0,v.releasedBy ? json(v.releasedBy) : null,v.releasedAt,v.id).run() }

  async createRecovery(v: RecoveryRecord) { await this.db.prepare('INSERT INTO recovery_records (id,workspace_id,task_id,run_id,outcome,status,strategy,created_at,completed_at,metadata) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.taskId,v.runId,v.outcome,v.status,v.strategy,v.createdAt,v.completedAt,json(v.metadata)).run() }
  getRecovery(id: string) { return this.one('SELECT * FROM recovery_records WHERE id=?', id, recovery) }
  listRecoveries() { return this.many('SELECT * FROM recovery_records ORDER BY created_at DESC LIMIT 500', recovery) }
  async saveRecovery(v: RecoveryRecord) { await this.db.prepare('UPDATE recovery_records SET outcome=?,status=?,strategy=?,completed_at=?,metadata=? WHERE id=?').bind(v.outcome,v.status,v.strategy,v.completedAt,json(v.metadata),v.id).run() }

  async createTelemetry(v: TelemetryRecord) { await this.db.prepare('INSERT INTO telemetry (id,correlation_id,task_id,run_id,workspace_id,capability_id,actor,timestamp,duration_ms,status,error_class,retry_count,policy_outcome,metadata) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.correlationId,v.taskId,v.runId,v.workspaceId,v.capabilityId,json(v.actor),v.timestamp,v.durationMs,v.status,v.errorClass,v.retryCount,v.policyOutcome,json(v.metadata)).run() }
  listTelemetry() { return this.many('SELECT * FROM telemetry ORDER BY timestamp DESC LIMIT 500', telemetry) }

  async createOutcome(v:OutcomeRecord){await this.db.prepare('INSERT INTO outcome_records VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.taskId,v.runId,v.capabilityId,v.versionId,v.status,v.startedAt,v.completedAt,v.durationMs,v.attempts,v.retries,v.policyOutcome,v.errorClass,json(v.metrics),v.sourceType,v.sourceId,v.verified?1:0,v.capturedAt).run()}
  getOutcome(id:string){return this.one('SELECT * FROM outcome_records WHERE id=?',id,outcome)}
  listOutcomes(){return this.many('SELECT * FROM outcome_records ORDER BY captured_at DESC LIMIT 500',outcome)}
  async createLearningSignal(v:LearningSignal){await this.db.prepare('INSERT INTO learning_signals VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.targetType,v.targetId,v.versionId,v.signalType,v.value,v.sampleSize,json(v.outcomeRefs),v.validationStatus,v.confidence,v.createdAt).run()}
  getLearningSignal(id:string){return this.one('SELECT * FROM learning_signals WHERE id=?',id,signal)}
  listLearningSignals(){return this.many('SELECT * FROM learning_signals ORDER BY created_at DESC LIMIT 500',signal)}
  async createOptimizationProposal(v:OptimizationProposal){await this.db.prepare('INSERT INTO optimization_proposals VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.targetType,v.targetId,v.reason,json(v.evidenceRefs),json(v.currentConfig),json(v.proposedConfig),json(v.expectedEffect),v.riskClass,v.status,v.baseRevisionId,v.appliedRevisionId,v.approvalRef,v.createdAt,v.reviewedAt,v.appliedAt,v.revertedAt,null).run()}
  getOptimizationProposal(id:string){return this.one('SELECT * FROM optimization_proposals WHERE id=?',id,proposal)}
  listOptimizationProposals(){return this.many('SELECT * FROM optimization_proposals ORDER BY created_at DESC LIMIT 500',proposal)}
  async saveOptimizationProposal(v:OptimizationProposal){await this.db.prepare('UPDATE optimization_proposals SET status=?,applied_revision_id=?,approval_ref=?,reviewed_at=?,applied_at=?,reverted_at=? WHERE id=?').bind(v.status,v.appliedRevisionId,v.approvalRef,v.reviewedAt,v.appliedAt,v.revertedAt,v.id).run()}
  async createConfigurationRevision(v:ConfigurationRevision){await this.db.prepare('INSERT INTO configuration_revisions VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.targetType,v.targetId,v.version,json(v.config),v.previousRevisionId,v.proposalId,v.status,v.createdAt,v.activatedAt).run()}
  getConfigurationRevision(id:string){return this.one('SELECT * FROM configuration_revisions WHERE id=?',id,revision)}
  listConfigurationRevisions(){return this.many('SELECT * FROM configuration_revisions ORDER BY version DESC LIMIT 500',revision)}
  async saveConfigurationRevision(v:ConfigurationRevision){await this.db.prepare('UPDATE configuration_revisions SET status=?,activated_at=? WHERE id=?').bind(v.status,v.activatedAt,v.id).run()}
  async createPerformanceMeasurement(v:PerformanceMeasurement){await this.db.prepare('INSERT INTO performance_measurements VALUES (?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.targetType,v.targetId,v.versionId,v.period,json(v.outcomeRefs),json(v.metrics),v.measuredAt).run()}
  getPerformanceMeasurement(id:string){return this.one('SELECT * FROM performance_measurements WHERE id=?',id,measurement)}
  listPerformanceMeasurements(){return this.many('SELECT * FROM performance_measurements ORDER BY measured_at DESC LIMIT 500',measurement)}
  async createCapabilityPromotion(v:CapabilityPromotion){await this.db.prepare('INSERT INTO capability_promotions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(v.id,v.workspaceId,v.capabilityId,v.ownerId,json(v.provenanceRefs),json(v.performanceMeasurementIds),json(v.securityContract),json(v.scope),v.status,v.approvalRef,v.createdAt,v.reviewedAt,v.promotedAt,null).run()}
  getCapabilityPromotion(id:string){return this.one('SELECT * FROM capability_promotions WHERE id=?',id,promotion)}
  listCapabilityPromotions(){return this.many('SELECT * FROM capability_promotions ORDER BY created_at DESC LIMIT 500',promotion)}
  async saveCapabilityPromotion(v:CapabilityPromotion){await this.db.prepare('UPDATE capability_promotions SET status=?,approval_ref=?,reviewed_at=?,promoted_at=? WHERE id=?').bind(v.status,v.approvalRef,v.reviewedAt,v.promotedAt,v.id).run()}

  async appendEvent(v: AuditEvent) { await this.db.prepare('INSERT INTO events (id,type,actor,workspace_id,resource_type,resource_id,timestamp,metadata) VALUES (?,?,?,?,?,?,?,?)').bind(v.id,v.type,json(v.actor),v.workspaceId,v.resourceType,v.resourceId,v.timestamp,json(v.metadata)).run() }
  getEvent(id: string) { return this.one('SELECT * FROM events WHERE id=?', id, event) }
  listEvents() { return this.many('SELECT * FROM events ORDER BY timestamp DESC LIMIT 500', event) }
}
