import { conflict, forbidden, invalid, notFound } from '../domain/errors'
import type { Actor, AuditEvent, Capability, CapabilityPromotion, ConfigurationRevision, EventType, LearningSignal, OptimizationProposal, OutcomeRecord, PerformanceMeasurement, RiskLevel } from '../domain/models'
import { evaluateAuthorization } from '../policy/evaluator'
import type { Repository } from '../ports/repository'
import { assertNoPlaintextSecrets, redactSecrets } from '../security/secrets'
import { newId, now } from '../shared/ids'
import { SafetyController } from './safety-controller'

type Json = Record<string, unknown>
type TargetType = 'CAPABILITY' | 'WORKFLOW'
const terminalRuns = new Set(['COMPLETED', 'FAILED', 'CANCELLED', 'BLOCKED'])
const allowedConfig = new Set(['description', 'inputSchema', 'outputSchema'])

export class LearningEngine {
  private readonly safety: SafetyController
  constructor(private readonly repo: Repository, private readonly ownerId = 'owner_halstral', safety?: SafetyController) { this.safety = safety ?? new SafetyController(repo, ownerId) }

  private owner(actor: Actor) { if (actor.type !== 'OWNER' || actor.id !== this.ownerId) throw forbidden('Only the owner may mutate learning state') }
  private async audit(type: EventType, actor: Actor, workspaceId: string, resourceType: string, resourceId: string, metadata: Json = {}) {
    assertNoPlaintextSecrets(metadata)
    const event: AuditEvent = { id: newId('evt'), type, actor, workspaceId, resourceType, resourceId, timestamp: now(), metadata: redactSecrets(metadata) as Json }
    await this.repo.appendEvent(event)
  }
  private async inspect(actor: Actor, workspaceId: string, resource: string) {
    if (actor.type === 'OWNER' && actor.id === this.ownerId) return
    const decision = evaluateAuthorization({ actor, ownerId: this.ownerId, workspaceId, resource, action: 'read', policies: await this.repo.listPolicies() })
    await this.audit(decision.effect === 'ALLOW' ? 'AUTHORIZATION_GRANTED' : 'AUTHORIZATION_DENIED', actor, workspaceId, 'authorization', resource, { action: 'read', outcome: decision.effect, reason: decision.reason })
    if (decision.effect === 'DENY') throw forbidden(`Authorization denied: ${decision.reason}`)
  }
  private async workspaceActive(workspaceId: string) { const workspace = await this.repo.getWorkspace(workspaceId); if (!workspace) throw notFound('Workspace'); if (workspace.status !== 'ACTIVE') throw forbidden(`${workspace.status} workspace cannot apply learning changes`); return workspace }
  private config(capability: Capability): Json { return { description: capability.description, inputSchema: capability.inputSchema, outputSchema: capability.outputSchema } }
  private same(a: Json, b: Json) { return JSON.stringify(a) === JSON.stringify(b) }
  private async capability(workspaceId: string, id: string) { const capability = await this.repo.getCapability(id); if (!capability) throw notFound('Capability'); if (capability.workspaceId !== workspaceId) throw forbidden('Cross-workspace learning is denied by default'); return capability }
  private async activeRevision(workspaceId: string, targetType: TargetType, targetId: string) { return (await this.repo.listConfigurationRevisions()).filter((v) => v.workspaceId === workspaceId && v.targetType === targetType && v.targetId === targetId && v.status === 'ACTIVE').sort((a,b) => b.version-a.version)[0] ?? null }

  async captureOutcome(input: { workspaceId: string; runId: string; capabilityId: string; versionId?: string; metrics?: Json; verified?: boolean; sourceType?: OutcomeRecord['sourceType']; sourceId?: string }, actor: Actor) {
    this.owner(actor); assertNoPlaintextSecrets(input); await this.workspaceActive(input.workspaceId)
    const run = await this.repo.getRun(input.runId); if (!run || run.workspaceId !== input.workspaceId) throw notFound('Workspace-scoped run')
    if (!terminalRuns.has(run.status)) throw conflict('Only terminal execution outcomes may be captured')
    const task = await this.repo.getTask(run.taskId); if (!task || task.workspaceId !== input.workspaceId) throw forbidden('Outcome provenance does not match workspace')
    await this.capability(input.workspaceId, input.capabilityId)
    const results = (await this.repo.listResults()).filter((r) => r.runId === run.id && r.workspaceId === input.workspaceId)
    const sourceId = input.sourceId ?? results[0]?.id ?? run.id
    const sourceType = input.sourceType ?? (results[0] ? 'EXECUTION_RESULT' : 'RUN')
    if (sourceType === 'EXECUTION_RESULT' && !results.some((r) => r.id === sourceId)) throw invalid('Execution-result provenance is not valid for this run')
    const started = run.startedAt ?? run.createdAt; const completed = run.completedAt ?? run.updatedAt
    const numericMetrics = Object.fromEntries(Object.entries(input.metrics ?? {}).filter((entry): entry is [string, number] => typeof entry[1] === 'number' && Number.isFinite(entry[1])))
    const status: OutcomeRecord['status'] = run.status === 'COMPLETED' ? 'SUCCEEDED' : run.status as OutcomeRecord['status']
    const revision = await this.activeRevision(input.workspaceId, 'CAPABILITY', input.capabilityId)
    const outcome: OutcomeRecord = { id: newId('outcome'), workspaceId: input.workspaceId, taskId: task.id, runId: run.id, capabilityId: input.capabilityId, versionId: input.versionId ?? revision?.id ?? 'baseline', status, startedAt: started, completedAt: completed, durationMs: Math.max(0, Date.parse(completed)-Date.parse(started)), attempts: run.attempt, retries: Math.max(0, run.attempt-1), policyOutcome: run.status === 'BLOCKED' ? 'DENY' : 'ALLOW', errorClass: null, metrics: numericMetrics, sourceType, sourceId, verified: input.verified === true, capturedAt: now() }
    await this.repo.createOutcome(outcome); await this.audit('OUTCOME_CAPTURED', actor, outcome.workspaceId, 'outcome', outcome.id, { runId: run.id, sourceType, sourceId, verified: outcome.verified, versionId: outcome.versionId }); return outcome
  }

  async listOutcomes(actor: Actor, workspaceId?: string) { if (!workspaceId) this.owner(actor); else await this.inspect(actor, workspaceId, 'outcome:*'); return (await this.repo.listOutcomes()).filter((x) => !workspaceId || x.workspaceId === workspaceId) }

  async deriveSignals(workspaceId: string, targetId: string, actor: Actor) {
    this.owner(actor); await this.workspaceActive(workspaceId); await this.capability(workspaceId, targetId)
    const all = (await this.repo.listOutcomes()).filter((x) => x.workspaceId === workspaceId && x.capabilityId === targetId)
    const verified = all.filter((x) => x.verified); if (!verified.length) throw invalid('Verified outcome evidence is required')
    const refs = verified.map((x) => x.id); const n = verified.length; const versionId = verified[0].versionId
    const definitions: Array<[LearningSignal['signalType'], number]> = [
      ['SUCCESS_RATE', verified.filter((x)=>x.status==='SUCCEEDED').length/n], ['FAILURE_RATE', verified.filter((x)=>x.status==='FAILED').length/n],
      ['AVERAGE_LATENCY', verified.reduce((s,x)=>s+x.durationMs,0)/n], ['RETRY_RATE', verified.reduce((s,x)=>s+x.retries,0)/n],
      ['TIMEOUT_RATE', verified.filter((x)=>x.errorClass==='TIMEOUT').length/n], ['RECOVERY_RATE', verified.filter((x)=>x.status==='RECOVERED').length/n],
      ['POLICY_DENIAL_RATE', verified.filter((x)=>x.policyOutcome==='DENY').length/n],
    ]
    const signals: LearningSignal[] = []
    for (const [signalType, value] of definitions) { const signal: LearningSignal = { id: newId('signal'), workspaceId, targetType: 'CAPABILITY', targetId, versionId, signalType, value, sampleSize: n, outcomeRefs: refs, validationStatus: 'VERIFIED', confidence: Math.min(1, n/10), createdAt: now() }; await this.repo.createLearningSignal(signal); await this.audit('LEARNING_SIGNAL_CREATED', actor, workspaceId, 'learning_signal', signal.id, { signalType, outcomeRefs: refs, validationStatus: signal.validationStatus }); signals.push(signal) }
    return signals
  }
  async listSignals(actor: Actor, workspaceId?: string) { if (!workspaceId) this.owner(actor); else await this.inspect(actor, workspaceId, 'learning-signal:*'); return (await this.repo.listLearningSignals()).filter((x)=>!workspaceId||x.workspaceId===workspaceId) }

  async createProposal(input: { workspaceId: string; targetType?: TargetType; targetId: string; reason: string; evidenceRefs: string[]; proposedConfig: Json; expectedEffect?: Json; riskClass?: RiskLevel }, actor: Actor) {
    this.owner(actor); assertNoPlaintextSecrets(input); await this.workspaceActive(input.workspaceId)
    const targetType = input.targetType ?? 'CAPABILITY'; if (targetType !== 'CAPABILITY') throw invalid('Workflow targets are not yet backed by a mutable registry')
    const capability = await this.capability(input.workspaceId, input.targetId); if (!input.reason?.trim() || !input.evidenceRefs?.length) throw invalid('Reason and evidence references are required')
    for (const key of Object.keys(input.proposedConfig)) if (!allowedConfig.has(key)) throw forbidden(`Protected configuration field cannot be optimized: ${key}`)
    const signals = await Promise.all(input.evidenceRefs.map((id)=>this.repo.getLearningSignal(id)))
    if (signals.some((x)=>!x || x.workspaceId!==input.workspaceId || x.targetId!==input.targetId || x.validationStatus!=='VERIFIED')) throw invalid('Only verified workspace-scoped signals may support a proposal')
    let base = await this.activeRevision(input.workspaceId, targetType, input.targetId)
    if (!base) { base = { id:newId('rev'), workspaceId:input.workspaceId,targetType,targetId:input.targetId,version:1,config:this.config(capability),previousRevisionId:null,proposalId:null,status:'ACTIVE',createdAt:now(),activatedAt:now() }; await this.repo.createConfigurationRevision(base) }
    const proposal: OptimizationProposal = { id:newId('proposal'),workspaceId:input.workspaceId,targetType,targetId:input.targetId,reason:input.reason.trim(),evidenceRefs:[...new Set(input.evidenceRefs)],currentConfig:base.config,proposedConfig:input.proposedConfig,expectedEffect:input.expectedEffect??{},riskClass:input.riskClass??capability.riskLevel,status:'DRAFT',baseRevisionId:base.id,appliedRevisionId:null,approvalRef:null,createdAt:now(),reviewedAt:null,appliedAt:null,revertedAt:null }
    await this.repo.createOptimizationProposal(proposal); return proposal
  }
  async listProposals(actor: Actor, workspaceId?: string) { if (!workspaceId) this.owner(actor); else await this.inspect(actor,workspaceId,'optimization-proposal:*'); return (await this.repo.listOptimizationProposals()).filter((x)=>!workspaceId||x.workspaceId===workspaceId) }
  async submitProposal(id:string, actor:Actor) { this.owner(actor); const p=await this.repo.getOptimizationProposal(id); if(!p)throw notFound('Optimization proposal'); if(p.status!=='DRAFT')throw conflict('Only draft proposals may be submitted'); p.status='PENDING_REVIEW'; await this.repo.saveOptimizationProposal(p); await this.audit('OPTIMIZATION_PROPOSED',actor,p.workspaceId,'optimization_proposal',p.id,{evidenceRefs:p.evidenceRefs,targetId:p.targetId,riskClass:p.riskClass}); return p }
  async decideProposal(id:string, approved:boolean, approvalRef:string, actor:Actor) { this.owner(actor); const p=await this.repo.getOptimizationProposal(id); if(!p)throw notFound('Optimization proposal'); if(p.status!=='PENDING_REVIEW')throw conflict('Proposal is not pending review'); if(!approvalRef.trim())throw invalid('approvalRef is required'); p.status=approved?'APPROVED':'REJECTED';p.approvalRef=approvalRef;p.reviewedAt=now();await this.repo.saveOptimizationProposal(p);await this.audit(approved?'OPTIMIZATION_APPROVED':'OPTIMIZATION_REJECTED',actor,p.workspaceId,'optimization_proposal',p.id,{approvalRef});return p }
  async applyProposal(id:string, actor:Actor) { this.owner(actor); const p=await this.repo.getOptimizationProposal(id);if(!p)throw notFound('Optimization proposal');if(p.status!=='APPROVED'||!p.approvalRef)throw forbidden('Only explicitly approved proposals may be applied');await this.workspaceActive(p.workspaceId);const cap=await this.capability(p.workspaceId,p.targetId);if(cap.status!=='ACTIVE')throw forbidden('Target capability is not active');await this.safety.assertNoSafeStop({correlationId:newId('corr'),workspaceId:p.workspaceId,taskId:`optimization:${p.id}`,capabilityId:cap.id});const current=await this.activeRevision(p.workspaceId,p.targetType,p.targetId);if(!current||current.id!==p.baseRevisionId||!this.same(current.config,p.currentConfig)||!this.same(this.config(cap),p.currentConfig))throw conflict('Target configuration changed after proposal review');const decision=evaluateAuthorization({actor,ownerId:this.ownerId,workspaceId:p.workspaceId,resource:`capability:${cap.id}`,action:'optimize',policies:await this.repo.listPolicies()});if(decision.effect!=='ALLOW')throw forbidden('Optimization policy denied application');current.status='REVERTED';await this.repo.saveConfigurationRevision(current);const config={...p.currentConfig,...p.proposedConfig};const revision:ConfigurationRevision={id:newId('rev'),workspaceId:p.workspaceId,targetType:p.targetType,targetId:p.targetId,version:current.version+1,config,previousRevisionId:current.id,proposalId:p.id,status:'ACTIVE',createdAt:now(),activatedAt:now()};await this.repo.createConfigurationRevision(revision);cap.description=String(config.description??cap.description);cap.inputSchema=(config.inputSchema??cap.inputSchema) as Json;cap.outputSchema=(config.outputSchema??cap.outputSchema) as Json;cap.updatedAt=now();await this.repo.saveCapability(cap);p.status='APPLIED';p.appliedRevisionId=revision.id;p.appliedAt=now();await this.repo.saveOptimizationProposal(p);await this.audit('OPTIMIZATION_APPLIED',actor,p.workspaceId,'optimization_proposal',p.id,{approvalRef:p.approvalRef,revisionId:revision.id,previousRevisionId:current.id});return {proposal:p,revision} }
  async revertProposal(id:string, actor:Actor, disable=false) { this.owner(actor);const p=await this.repo.getOptimizationProposal(id);if(!p)throw notFound('Optimization proposal');if(p.status!=='APPLIED')throw conflict('Only applied proposals may be reverted or disabled');const applied=p.appliedRevisionId?await this.repo.getConfigurationRevision(p.appliedRevisionId):null;const previous=applied?.previousRevisionId?await this.repo.getConfigurationRevision(applied.previousRevisionId):null;if(!applied||!previous)throw conflict('Recoverable prior revision is missing');const cap=await this.capability(p.workspaceId,p.targetId);applied.status=disable?'DISABLED':'REVERTED';previous.status='ACTIVE';previous.activatedAt=now();await this.repo.saveConfigurationRevision(applied);await this.repo.saveConfigurationRevision(previous);cap.description=String(previous.config.description??cap.description);cap.inputSchema=(previous.config.inputSchema??cap.inputSchema) as Json;cap.outputSchema=(previous.config.outputSchema??cap.outputSchema) as Json;cap.updatedAt=now();await this.repo.saveCapability(cap);p.status=disable?'DISABLED':'REVERTED';p.revertedAt=now();await this.repo.saveOptimizationProposal(p);await this.audit('OPTIMIZATION_REVERTED',actor,p.workspaceId,'optimization_proposal',p.id,{disabled:disable,restoredRevisionId:previous.id});return p }

  async measure(input:{workspaceId:string;targetId:string;versionId:string;period:'BASELINE'|'POST_CHANGE';outcomeRefs:string[]},actor:Actor){this.owner(actor);if(!input.outcomeRefs.length)throw invalid('Outcome evidence is required');const outcomes=await Promise.all(input.outcomeRefs.map((id)=>this.repo.getOutcome(id)));if(outcomes.some((x)=>!x||!x.verified||x.workspaceId!==input.workspaceId||x.capabilityId!==input.targetId||x.versionId!==input.versionId))throw invalid('Measurement evidence must be verified, scoped, and version-attributed');const values=outcomes as OutcomeRecord[];const n=values.length;const metrics={successRate:values.filter((x)=>x.status==='SUCCEEDED').length/n,averageLatencyMs:values.reduce((s,x)=>s+x.durationMs,0)/n,retryRate:values.reduce((s,x)=>s+x.retries,0)/n,timeoutRate:values.filter((x)=>x.errorClass==='TIMEOUT').length/n,recoveryRate:values.filter((x)=>x.status==='RECOVERED').length/n};const measurement:PerformanceMeasurement={id:newId('measure'),workspaceId:input.workspaceId,targetType:'CAPABILITY',targetId:input.targetId,versionId:input.versionId,period:input.period,outcomeRefs:input.outcomeRefs,metrics,measuredAt:now()};await this.repo.createPerformanceMeasurement(measurement);await this.audit('PERFORMANCE_MEASURED',actor,input.workspaceId,'performance_measurement',measurement.id,{versionId:input.versionId,period:input.period,outcomeRefs:input.outcomeRefs});return measurement}
  async comparePerformance(workspaceId:string,targetId:string,actor:Actor){await this.inspect(actor,workspaceId,'performance:*');const items=(await this.repo.listPerformanceMeasurements()).filter((x)=>x.workspaceId===workspaceId&&x.targetId===targetId);const baseline=items.filter((x)=>x.period==='BASELINE').at(-1);const postChange=items.filter((x)=>x.period==='POST_CHANGE').at(-1);if(!baseline||!postChange)throw notFound('Baseline and post-change measurements');const delta=Object.fromEntries(Object.keys(baseline.metrics).map((k)=>[k,(postChange.metrics[k]??0)-(baseline.metrics[k]??0)]));return{baseline,postChange,delta}}
  async listRevisions(actor:Actor,workspaceId?:string){if(!workspaceId)this.owner(actor);else await this.inspect(actor,workspaceId,'revision:*');return(await this.repo.listConfigurationRevisions()).filter((x)=>!workspaceId||x.workspaceId===workspaceId)}

  async proposePromotion(input:{workspaceId:string;capabilityId:string;provenanceRefs:string[];performanceMeasurementIds:string[];securityContract:Json;scope:Json},actor:Actor){this.owner(actor);assertNoPlaintextSecrets(input);await this.workspaceActive(input.workspaceId);const cap=await this.capability(input.workspaceId,input.capabilityId);if(!input.provenanceRefs.length||!input.performanceMeasurementIds.length||!Object.keys(input.securityContract).length||!Object.keys(input.scope).length)throw invalid('Ownership, provenance, security, scope, and performance evidence are required');for(const id of input.provenanceRefs){const outcome=await this.repo.getOutcome(id);if(!outcome||!outcome.verified||outcome.workspaceId!==input.workspaceId)throw invalid('Promotion provenance must be verified and workspace-scoped')}for(const id of input.performanceMeasurementIds){const m=await this.repo.getPerformanceMeasurement(id);if(!m||m.workspaceId!==input.workspaceId||m.targetId!==cap.id)throw invalid('Promotion performance evidence is invalid')}const promotion:CapabilityPromotion={id:newId('promotion'),workspaceId:input.workspaceId,capabilityId:cap.id,ownerId:this.ownerId,provenanceRefs:input.provenanceRefs,performanceMeasurementIds:input.performanceMeasurementIds,securityContract:input.securityContract,scope:input.scope,status:'PROPOSED',approvalRef:null,createdAt:now(),reviewedAt:null,promotedAt:null};await this.repo.createCapabilityPromotion(promotion);await this.audit('CAPABILITY_PROMOTION_PROPOSED',actor,input.workspaceId,'capability_promotion',promotion.id,{capabilityId:cap.id,provenanceRefs:input.provenanceRefs});return promotion}
  async decidePromotion(id:string,approved:boolean,approvalRef:string,actor:Actor){this.owner(actor);const p=await this.repo.getCapabilityPromotion(id);if(!p)throw notFound('Capability promotion');if(p.status!=='PROPOSED')throw conflict('Promotion is not pending review');if(!approvalRef.trim())throw invalid('approvalRef is required');p.status=approved?'APPROVED':'REJECTED';p.approvalRef=approvalRef;p.reviewedAt=now();await this.repo.saveCapabilityPromotion(p);if(!approved)await this.audit('CAPABILITY_PROMOTION_REJECTED',actor,p.workspaceId,'capability_promotion',p.id,{approvalRef});return p}
  async promote(id:string,actor:Actor){this.owner(actor);const p=await this.repo.getCapabilityPromotion(id);if(!p)throw notFound('Capability promotion');if(p.status!=='APPROVED'||!p.approvalRef)throw forbidden('Promotion requires explicit approval');await this.workspaceActive(p.workspaceId);const cap=await this.capability(p.workspaceId,p.capabilityId);if(cap.status!=='ACTIVE')throw forbidden('Disabled capability cannot be promoted');await this.safety.assertNoSafeStop({correlationId:newId('corr'),workspaceId:p.workspaceId,taskId:`promotion:${p.id}`,capabilityId:cap.id});p.status='PROMOTED';p.promotedAt=now();await this.repo.saveCapabilityPromotion(p);await this.audit('CAPABILITY_PROMOTED',actor,p.workspaceId,'capability_promotion',p.id,{capabilityId:p.capabilityId,approvalRef:p.approvalRef});return p}
  async listPromotions(actor:Actor,workspaceId?:string){if(!workspaceId)this.owner(actor);else await this.inspect(actor,workspaceId,'capability-promotion:*');return(await this.repo.listCapabilityPromotions()).filter((x)=>!workspaceId||x.workspaceId===workspaceId)}
}
